{% set name = "dpdispatcher" %}
{% set version = "0.6.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 709781b1386acc6d38c94de006fdf822c613cb833b3e3a838627449bd6f64c70

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dpdisp = dpdispatcher.dpdisp:main

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm

  run:
    - python >=3.7
    - dargs >=0.4.1
    - paramiko
    - requests
    - tqdm >=4.9.0
    - pyyaml

test:
  imports:
    - dpdispatcher
  commands:
    - dpdisp -h
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deepmodeling/dpdispatcher
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: generate HPC scheduler systems jobs input scripts and submit these scripts to HPC systems and poke until they finish
  doc_url: https://docs.deepmodeling.com/projects/dpdispatcher/
  dev_url: https://github.com/deepmodeling/dpdispatcher

extra:
  recipe-maintainers:
    - njzjz
