{% set name = "dpdispatcher" %}
{% set version = "0.6.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 78551446e2783d78c1f9fcfed761e5f1a4505e5569274dd049911a6c8d5ddc5c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dpdisp = dpdispatcher.dpdisp:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm

  run:
    - python >={{ python_min }}
    - dargs >=0.4.1
    - paramiko
    - requests
    - tqdm >=4.9.0
    - pyyaml
    - tomli

test:
  imports:
    - dpdispatcher
  commands:
    - dpdisp -h
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/deepmodeling/dpdispatcher
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: generate HPC scheduler systems jobs input scripts and submit these scripts to HPC systems and poke until they finish
  doc_url: https://docs.deepmodeling.com/projects/dpdispatcher/
  dev_url: https://github.com/deepmodeling/dpdispatcher

extra:
  recipe-maintainers:
    - njzjz
