{% set name = "dpdispatcher" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b6cabc70391aceee4095381f8db0ab20a9abcc2849a06259edb58a565dda04ec

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dpdisp = dpdispatcher.dpdisp:main

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm

  run:
    - python >=3.6
    - dargs
    - paramiko
    - requests
    - tqdm

test:
  imports:
    - dpdispatcher
  commands:
    - dpdisp -h

about:
  home: https://github.com/deepmodeling/dpdispatcher
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: generate HPC scheduler systems jobs input scripts and submit these scripts to HPC systems and poke until they finish
  doc_url: https://docs.deepmodeling.com/projects/dpdispatcher/
  dev_url: https://github.com/deepmodeling/dpdispatcher

extra:
  recipe-maintainers:
    - njzjz
